### ISSUE TITLE
"Send" button on Contact subpage does not work.

### ISSUE THREAD

**Issue by aslanchek** [netverify/netverify.github.io#35]
Hello there!
I was going to inquire about formal network verification related issues on [Contact Page](https://netverify.fun/contact.html), but unfortunately it seems that button does not work. It leads to invalid form on [formspree.io](https://formspree.io/wowthemesnet@gmail.com).

**Comment by ratulm** [comment]
Fixed in #36. Thanks for reporting the problem.
